apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: registry-vpc.cn-shanghai.aliyuncs.com/clioude/worker:async
        name: worker
        env:
        - name: BACKEND_URL
          value: http://server:8080/api/heartbeat
        - name: SERVICE_URL
          value: ws://worker:8080
        - name: TOKEN
          value: YOUR_TOKEN_HERE
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        volumeMounts:
        - mountPath: /tmp
          name: worker-tmpfs0
      volumes:
      - emptyDir:
          medium: Memory
        name: worker-tmpfs0
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
  - port: 8080
  selector:
    app: worker